---
title: "Croissance bactérienne"
author: "___"
date: "___"
output: html_document
---

```{r setup}
SciViews::R("model", lang = "fr")
```

## Introduction

<!--% Vous savez quoi mettre ici...-->

## Analyse

### Description

<!--% Importez, remaniez (renommer les variables, ajouter les labels et unités: LOG1ON est sans unités -nombre de bactéries en log10-, t est en jours). Ensuite décrivez ces données numériquement et à l'aide du graphique le plus adéquat -->

```{r import}
growth <- ___
```

<!--% Décrivez ces données -->

```{r describe}

```

<!--% Effectuez le graphique le plus adéquat ici -->

```{r plot}

```

<!--% Interprétez ce graphique en maximum 2 phrases. -->

### Modélisation

<!--% Essayez plusieurs modèles (au moins trois), comparez-les entre eux et décidez lequel est le plus adéquat. Ecrivez l'équation paramétrée de chaque modèle. Interprétez chacun de vos résultats. -->

## Discussion et conclusions

<!--% Explicitez ici votre choix du meilleur modèle et pourquoi c'est celui-là -->
